# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 34247c28e4697561467f16421096246f7a8473a2375496634ad7b9dfbeb562248f779bdc2717de8135a36870f14b162f6f6f23ae2b3e88779fbd6ff0940b688f

test:
  secret_key_base: a9e999e224cb0e554a5dfac6b0789c53a9a3454c248a61863851bc428a8ec0e1569af9721a767ba10bcdbc15b48e32e1feeb31a78dd210b24b4eb3c1bce6b42a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
